using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using ProjectSomeren.Models;
using System.Diagnostics;

namespace ProjectSomeren.Controllers
{
    public class DrinksController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly string _connectionString;

        public DrinksController(IConfiguration configuration)
        {
            _configuration = configuration;
            _connectionString = _configuration.GetConnectionString("DefaultConnection");
        }

        // Display all Drinks with optional filtering by last name
        public IActionResult Index(string searchName)
        {
            List<Drink> drinks = new List<Drink>();

            string query = "SELECT drink_Id, name, price, vat, stock FROM Drink";

            if (!string.IsNullOrEmpty(searchName))
            {
                query += " WHERE name LIKE @SearchName";
            }

            query += " ORDER BY name ";

            using (SqlConnection connection = new SqlConnection(_connectionString))
            {
                SqlCommand command = new SqlCommand(query, connection);

                if (!string.IsNullOrEmpty(searchName))
                {
                    command.Parameters.AddWithValue("@SearchName", "%" + searchName + "%");
                }

                connection.Open();

                using (SqlDataReader reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        Drink drink = new Drink
                        {
                            Drink_Id = reader.GetInt32(0),
                            Name = reader.IsDBNull(1) ? string.Empty : reader.GetString(1),
                            Price = reader.IsDBNull(2) ? 0 : reader.GetDecimal(2),
                            Vat = reader.IsDBNull(3) ? 0 : reader.GetInt32(3),
                            Stock = reader.IsDBNull(4) ? 0 :  reader.GetInt32(4),

                        };
                        drinks.Add(drink);
                    }
                }
            }

            ViewData["SearchName"] = searchName;
            return View(drinks);
        }

        // GET: Display create form
        public IActionResult Create()
        {
            return View();
        }

        // POST: Add a new Drink
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Drink drink)
        {
            if (ModelState.IsValid)
            {
                using (SqlConnection connection = new SqlConnection(_connectionString))
                {
                    connection.Open();

                    // Check if a Drink with the same first and last name already exists
                    string checkDuplicateQuery = "SELECT COUNT(*) FROM drink WHERE first_name = @FirstName AND last_name = @Name";
                    SqlCommand checkDuplicateCommand = new SqlCommand(checkDuplicateQuery, connection);
                   checkDuplicateCommand.Parameters.AddWithValue("@Name", drink.Name ?? string.Empty);

                    int duplicateCount = (int)checkDuplicateCommand.ExecuteScalar();

                    if (duplicateCount > 0)
                    {
                        ModelState.AddModelError(string.Empty, $"A Drink with the name '{drink.Name}' already exists. Please use a different name or check the existing records.");
                        return View(drink);
                    }

                    // Insert the new Drink (drink_id will be auto-generated by the database)
                    string insertQuery = "INSERT INTO drink (name, Price, Vat, Stock,) VALUES (@Name, @Price, @Vat, @Stock)";
                    SqlCommand insertCommand = new SqlCommand(insertQuery, connection);
                  
                    insertCommand.Parameters.AddWithValue("@Name", drink.Name ?? string.Empty);
                    insertCommand.Parameters.AddWithValue("@Price", drink.Price);
                    insertCommand.Parameters.AddWithValue("@Vat", drink.Vat);
                    insertCommand.Parameters.AddWithValue("@Stock", drink.Stock);

                    insertCommand.ExecuteNonQuery();
                }

                return RedirectToAction(nameof(Index));
            }

            return View(drink);
        }

        // GET: Display edit form
        public IActionResult Edit(int id)
        {
            Drink drink = null;

            string query = "SELECT drink_Id, name, price, vat, stock FROM drink WHERE drink_id = @Id";

            using (SqlConnection connection = new SqlConnection(_connectionString))
            {
                SqlCommand command = new SqlCommand(query, connection);
                command.Parameters.AddWithValue("@Id", id);
                connection.Open();

                using (SqlDataReader reader = command.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        drink = new Drink
                        {
                            Drink_Id = reader.GetInt32(0),
                            Name = reader.IsDBNull(1) ? string.Empty : reader.GetString(1),
                            Price = reader.IsDBNull(2) ? 0 : reader.GetDecimal(2),
                            Vat = reader.IsDBNull(3) ? 0 : reader.GetInt32(3),
                            Stock = reader.IsDBNull(4) ? 0 : reader.GetInt32(4),
                        };
                    }
                }
            }

            if (drink == null)
            {
                return NotFound();
            }

            return View(drink);
        }

        // POST: Update an existing Drink
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int drink_Id, Drink Drink)
        {
            if (drink_Id != Drink.Drink_Id)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                string query = "UPDATE drink SET , name = @Name, price = @Price, vat = @Vat, stock = @Stock, WHERE drink_id = @Id";

                using (SqlConnection connection = new SqlConnection(_connectionString))
                {
                    SqlCommand command = new SqlCommand(query, connection);
                    command.Parameters.AddWithValue("@Id", Drink.Drink_Id);
                    command.Parameters.AddWithValue("@Name", Drink.Name);
                    command.Parameters.AddWithValue("@Price", Drink.Price);
                    command.Parameters.AddWithValue("@Vat", Drink.Vat);
                    command.Parameters.AddWithValue("@Stock", Drink.Stock);
                    

                    connection.Open();
                    command.ExecuteNonQuery();
                }

                return RedirectToAction(nameof(Index));
            }

            return View(Drink);
        }

        // GET: Display delete confirmation
        public IActionResult Delete(int id)
        {
            Drink drink = null;

            string query = "SELECT drink_Id, name, price, vat, stock FROM Drinks WHERE drink_id = @Id";

            using (SqlConnection connection = new SqlConnection(_connectionString))
            {
                SqlCommand command = new SqlCommand(query, connection);
                command.Parameters.AddWithValue("@Id", id);
                connection.Open();

                using (SqlDataReader reader = command.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        drink = new Drink
                        {
                            Drink_Id = reader.GetInt32(0),
                            Name = reader.IsDBNull(1) ? string.Empty : reader.GetString(1),
                            Price = reader.IsDBNull(2) ? 0 : reader.GetDecimal(2),
                            Vat = reader.IsDBNull(3) ? 0 : reader.GetInt32(3),
                            Stock = reader.IsDBNull(4) ? 0 : reader.GetInt32(4),
                        };
                    }
                }
            }

            if (drink == null)
            {
                return NotFound();
            }

            return View(drink);
        }

        // POST: Remove an existing Drink
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            string query = "DELETE FROM drink WHERE drink_id = @Id";

            using (SqlConnection connection = new SqlConnection(_connectionString))
            {
                SqlCommand command = new SqlCommand(query, connection);
                command.Parameters.AddWithValue("@Id", id);

                connection.Open();
                command.ExecuteNonQuery();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}
