using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using ProjectSomeren.Models;

namespace ProjectSomeren.Controllers
{
    public class LecturersController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly string _connectionString;

        public LecturersController(IConfiguration configuration)
        {
            _configuration = configuration;
            _connectionString = _configuration.GetConnectionString("DefaultConnection");
        }

        // Display all lecturers with optional filtering by last name
        public IActionResult Index(string searchLastName)
        {
            List<Lecturer> lecturers = new List<Lecturer>();

            string query = "SELECT teacher_id, first_name, last_name, email, department, age, telephone_number FROM Teacher";
            
            if (!string.IsNullOrEmpty(searchLastName))
            {
                query += " WHERE last_name LIKE @SearchLastName";
            }
            
            query += " ORDER BY last_name, first_name";

            using (SqlConnection connection = new SqlConnection(_connectionString))
            {
                SqlCommand command = new SqlCommand(query, connection);
                
                if (!string.IsNullOrEmpty(searchLastName))
                {
                    command.Parameters.AddWithValue("@SearchLastName", "%" + searchLastName + "%");
                }
                
                connection.Open();

                using (SqlDataReader reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        Lecturer lecturer = new Lecturer
                        {
                            Id = reader.GetInt32(0),
                            FirstName = reader.IsDBNull(1) ? string.Empty : reader.GetString(1),
                            LastName = reader.IsDBNull(2) ? string.Empty : reader.GetString(2),
                            Email = reader.IsDBNull(3) ? string.Empty : reader.GetString(3),
                            Department = reader.IsDBNull(4) ? string.Empty : reader.GetString(4),
                            Age = reader.IsDBNull(5) ? 0 : reader.GetInt32(5),
                            TelephoneNumber = reader.IsDBNull(6) ? string.Empty : reader.GetString(6)
                        };
                        lecturers.Add(lecturer);
                    }
                }
            }

            ViewData["SearchLastName"] = searchLastName;
            return View(lecturers);
        }

        // GET: Display create form
        public IActionResult Create()
        {
            return View();
        }

        // POST: Add a new lecturer
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Lecturer lecturer)
        {
            if (ModelState.IsValid)
            {
                using (SqlConnection connection = new SqlConnection(_connectionString))
                {
                    connection.Open();

                    // Check if a lecturer with the same first and last name already exists
                    string checkDuplicateQuery = "SELECT COUNT(*) FROM Teacher WHERE first_name = @FirstName AND last_name = @LastName";
                    SqlCommand checkDuplicateCommand = new SqlCommand(checkDuplicateQuery, connection);
                    checkDuplicateCommand.Parameters.AddWithValue("@FirstName", lecturer.FirstName ?? string.Empty);
                    checkDuplicateCommand.Parameters.AddWithValue("@LastName", lecturer.LastName ?? string.Empty);

                    int duplicateCount = (int)checkDuplicateCommand.ExecuteScalar();

                    if (duplicateCount > 0)
                    {
                        ModelState.AddModelError(string.Empty, $"A lecturer with the name '{lecturer.FirstName} {lecturer.LastName}' already exists. Please use a different name or check the existing records.");
                        return View(lecturer);
                    }

                    // Insert the new lecturer (teacher_id will be auto-generated by the database)
                    string insertQuery = "INSERT INTO Teacher (first_name, last_name, email, department, age, telephone_number) VALUES (@FirstName, @LastName, @Email, @Department, @Age, @TelephoneNumber)";
                    SqlCommand insertCommand = new SqlCommand(insertQuery, connection);
                    insertCommand.Parameters.AddWithValue("@FirstName", lecturer.FirstName ?? string.Empty);
                    insertCommand.Parameters.AddWithValue("@LastName", lecturer.LastName ?? string.Empty);
                    insertCommand.Parameters.AddWithValue("@Email", lecturer.Email ?? string.Empty);
                    insertCommand.Parameters.AddWithValue("@Department", lecturer.Department ?? string.Empty);
                    insertCommand.Parameters.AddWithValue("@Age", lecturer.Age);
                    insertCommand.Parameters.AddWithValue("@TelephoneNumber", lecturer.TelephoneNumber ?? string.Empty);

                    insertCommand.ExecuteNonQuery();
                }

                return RedirectToAction(nameof(Index));
            }

            return View(lecturer);
        }

        // GET: Display edit form
        public IActionResult Edit(int id)
        {
            Lecturer lecturer = null;

            string query = "SELECT teacher_id, first_name, last_name, email, department, age, telephone_number FROM Teacher WHERE teacher_id = @Id";

            using (SqlConnection connection = new SqlConnection(_connectionString))
            {
                SqlCommand command = new SqlCommand(query, connection);
                command.Parameters.AddWithValue("@Id", id);
                connection.Open();

                using (SqlDataReader reader = command.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        lecturer = new Lecturer
                        {
                            Id = reader.GetInt32(0),
                            FirstName = reader.IsDBNull(1) ? string.Empty : reader.GetString(1),
                            LastName = reader.IsDBNull(2) ? string.Empty : reader.GetString(2),
                            Email = reader.IsDBNull(3) ? string.Empty : reader.GetString(3),
                            Department = reader.IsDBNull(4) ? string.Empty : reader.GetString(4),
                            Age = reader.IsDBNull(5) ? 0 : reader.GetInt32(5),
                            TelephoneNumber = reader.IsDBNull(6) ? string.Empty : reader.GetString(6)
                        };
                    }
                }
            }

            if (lecturer == null)
            {
                return NotFound();
            }

            return View(lecturer);
        }

        // POST: Update an existing lecturer
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Lecturer lecturer)
        {
            if (id != lecturer.Id)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                string query = "UPDATE Teacher SET first_name = @FirstName, last_name = @LastName, email = @Email, department = @Department, age = @Age, telephone_number = @TelephoneNumber WHERE teacher_id = @Id";

                using (SqlConnection connection = new SqlConnection(_connectionString))
                {
                    SqlCommand command = new SqlCommand(query, connection);
                    command.Parameters.AddWithValue("@Id", lecturer.Id);
                    command.Parameters.AddWithValue("@FirstName", lecturer.FirstName ?? string.Empty);
                    command.Parameters.AddWithValue("@LastName", lecturer.LastName ?? string.Empty);
                    command.Parameters.AddWithValue("@Email", lecturer.Email ?? string.Empty);
                    command.Parameters.AddWithValue("@Department", lecturer.Department ?? string.Empty);
                    command.Parameters.AddWithValue("@Age", lecturer.Age);
                    command.Parameters.AddWithValue("@TelephoneNumber", lecturer.TelephoneNumber ?? string.Empty);

                    connection.Open();
                    command.ExecuteNonQuery();
                }

                return RedirectToAction(nameof(Index));
            }

            return View(lecturer);
        }

        // GET: Display delete confirmation
        public IActionResult Delete(int id)
        {
            Lecturer lecturer = null;

            string query = "SELECT teacher_id, first_name, last_name, email, department, age, telephone_number FROM Teacher WHERE teacher_id = @Id";

            using (SqlConnection connection = new SqlConnection(_connectionString))
            {
                SqlCommand command = new SqlCommand(query, connection);
                command.Parameters.AddWithValue("@Id", id);
                connection.Open();

                using (SqlDataReader reader = command.ExecuteReader())
                {
                    if (reader.Read())
                    {
                        lecturer = new Lecturer
                        {
                            Id = reader.GetInt32(0),
                            FirstName = reader.IsDBNull(1) ? string.Empty : reader.GetString(1),
                            LastName = reader.IsDBNull(2) ? string.Empty : reader.GetString(2),
                            Email = reader.IsDBNull(3) ? string.Empty : reader.GetString(3),
                            Department = reader.IsDBNull(4) ? string.Empty : reader.GetString(4),
                            Age = reader.IsDBNull(5) ? 0 : reader.GetInt32(5),
                            TelephoneNumber = reader.IsDBNull(6) ? string.Empty : reader.GetString(6)
                        };
                    }
                }
            }

            if (lecturer == null)
            {
                return NotFound();
            }

            return View(lecturer);
        }

        // POST: Remove an existing lecturer
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            string query = "DELETE FROM Teacher WHERE teacher_id = @Id";

            using (SqlConnection connection = new SqlConnection(_connectionString))
            {
                SqlCommand command = new SqlCommand(query, connection);
                command.Parameters.AddWithValue("@Id", id);

                connection.Open();
                command.ExecuteNonQuery();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}
